// This prototype dataset only covers San Francisco. Real location-based results
// will require a larger geographic event dataset, a public events API, or a
// Cloudflare backend that retrieves events by city or ZIP code.
const mockWeeklyEventTemplates = [
  {
    id: 'bp-screening-westside-pharmacy',
    icon: '❤️',
    title: 'Free Blood Pressure Screening',
    dayOffset: 2,
    time: '10:00 AM',
    location: 'Walgreens – West Portal',
    address: '300 West Portal Ave, San Francisco, CA 94127',
    coordinates: { latitude: 37.7392, longitude: -122.4661 },
    distance: '1.2 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'blood-pressure'],
    details:
      'A drop-in community screening where visitors can check blood pressure and learn what numbers may be useful to discuss with a healthcare professional.',
    searchQuery: 'blood pressure screening pharmacy',
  },
  {
    id: 'community-heart-walk',
    icon: '🌿',
    title: 'Community Heart Walk',
    dayOffset: 3,
    time: '9:00 AM',
    location: 'Lake Merced Trail',
    address: 'Lake Merced, San Francisco, CA 94132',
    coordinates: { latitude: 37.7286, longitude: -122.493 },
    distance: '2.4 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'movement', 'mental'],
    details:
      'A beginner-friendly group walk focused on steady movement, social support, and building a repeatable weekly habit.',
    searchQuery: 'community heart walk walking trail',
  },
  {
    id: 'cholesterol-nutrition-class',
    icon: '🥗',
    title: 'Heart-Healthy Nutrition Class',
    dayOffset: 4,
    time: '6:00 PM',
    location: 'UCSF Mission Bay Community Center',
    address: '1675 Owens St, San Francisco, CA 94158',
    coordinates: { latitude: 37.7686, longitude: -122.393 },
    distance: '3.1 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'cholesterol', 'nutrition'],
    details:
      'A practical class on balanced meals, fiber-rich foods, and questions to bring up when discussing cholesterol screening.',
    searchQuery: 'heart healthy nutrition class wellness center',
  },
  {
    id: 'diabetes-prevention-workshop',
    icon: '🩸',
    title: 'Diabetes Prevention Workshop',
    dayOffset: 1,
    time: '6:00 PM',
    location: 'Sunset Recreation Center',
    address: '2201 Lawton St, San Francisco, CA 94122',
    coordinates: { latitude: 37.7576, longitude: -122.485 },
    distance: '2.0 miles',
    cost: 'Free',
    tags: ['diabetes', 'nutrition', 'movement'],
    details:
      'An educational workshop about healthy routines, glucose screening questions, and everyday prevention habits.',
    searchQuery: 'diabetes prevention workshop community center',
  },
  {
    id: 'healthy-cooking-demo',
    icon: '🥬',
    title: 'Healthy Cooking Demo',
    dayOffset: 5,
    time: '5:30 PM',
    location: 'Ferry Plaza Farmers Market',
    address: '1 Ferry Building, San Francisco, CA 94111',
    coordinates: { latitude: 37.7955, longitude: -122.3937 },
    distance: '4.4 miles',
    cost: 'Free',
    tags: ['diabetes', 'nutrition', 'cardiovascular'],
    details:
      'A hands-on cooking demo with simple meal ideas that support balanced nutrition and sustainable home routines.',
    searchQuery: 'healthy cooking demo farmers market',
  },
  {
    id: 'cancer-screening-talk',
    icon: '🧬',
    title: 'Cancer Screening Education Talk',
    dayOffset: 2,
    time: '12:30 PM',
    location: 'San Francisco Main Library',
    address: '100 Larkin St, San Francisco, CA 94102',
    coordinates: { latitude: 37.7793, longitude: -122.4157 },
    distance: '3.8 miles',
    cost: 'Free',
    tags: ['cancer', 'screening'],
    details:
      'A community education session about screening conversations, family history, and preparing questions for a primary-care visit.',
    searchQuery: 'cancer screening education seminar',
  },
  {
    id: 'genetic-counseling-info-session',
    icon: '🧬',
    title: 'Family History & Genetic Counseling Q&A',
    dayOffset: 6,
    time: '11:00 AM',
    location: 'UCSF Helen Diller Family Comprehensive Cancer Center',
    address: '1600 Divisadero St, San Francisco, CA 94115',
    coordinates: { latitude: 37.7849, longitude: -122.4392 },
    distance: '5.6 miles',
    cost: 'Free',
    tags: ['cancer', 'screening'],
    details:
      'An informational Q&A about when family patterns may be worth discussing with a healthcare professional or genetic counselor.',
    searchQuery: 'genetic counseling clinic family history',
  },
  {
    id: 'quit-support-group',
    icon: '🚭',
    title: 'Quit-Support Group',
    dayOffset: 1,
    time: '7:00 PM',
    location: 'San Francisco Community Health Center',
    address: '730 Polk St, San Francisco, CA 94109',
    coordinates: { latitude: 37.7835, longitude: -122.4191 },
    distance: '2.7 miles',
    cost: 'Free',
    tags: ['smoking', 'respiratory', 'cardiovascular'],
    details:
      'A supportive group for people exploring ways to reduce or stop smoking or vaping, with education and local quit resources.',
    searchQuery: 'smoking cessation support group',
  },
  {
    id: 'mindfulness-workshop',
    icon: '🧘',
    title: 'Mindfulness for Stress Workshop',
    dayOffset: 3,
    time: '6:30 PM',
    location: 'San Francisco Zen Center',
    address: '300 Page St, San Francisco, CA 94102',
    coordinates: { latitude: 37.7735, longitude: -122.4252 },
    distance: '1.9 miles',
    cost: 'Free',
    tags: ['mental', 'stress'],
    details:
      'A short workshop introducing breathing exercises, low-pressure reflection, and simple practices for stressful weeks.',
    searchQuery: 'mindfulness stress management workshop',
  },
  {
    id: 'community-yoga',
    icon: '🌱',
    title: 'Community Beginner Yoga',
    dayOffset: 4,
    time: '8:30 AM',
    location: 'Betty Ann Ong Chinese Recreation Center',
    address: '1199 Mason St, San Francisco, CA 94108',
    coordinates: { latitude: 37.793, longitude: -122.4116 },
    distance: '3.0 miles',
    cost: 'Paid',
    tags: ['mental', 'stress', 'movement'],
    details:
      'A gentle beginner class that supports movement, flexibility, and stress management without requiring prior experience.',
    searchQuery: 'beginner yoga class recreation center',
  },
  {
    id: 'family-wellness-fair',
    icon: '✨',
    title: 'Family Wellness Fair',
    dayOffset: 5,
    time: '10:00 AM',
    location: 'Moscone Center',
    address: '747 Howard St, San Francisco, CA 94103',
    coordinates: { latitude: 37.7842, longitude: -122.4016 },
    distance: '4.1 miles',
    cost: 'Free',
    tags: ['general', 'screening', 'nutrition', 'movement'],
    details:
      'A general wellness event with prevention education, community programs, and practical resources for building healthier routines.',
    searchQuery: 'community wellness fair',
  },
  {
    id: 'farmers-market-walkthrough',
    icon: '🍎',
    title: 'Farmers Market Wellness Walkthrough',
    dayOffset: 7,
    time: '9:30 AM',
    location: 'Alemany Farmers Market',
    address: '100 Alemany Blvd, San Francisco, CA 94110',
    coordinates: { latitude: 37.7373, longitude: -122.4105 },
    distance: '2.8 miles',
    cost: 'Free',
    tags: ['general', 'nutrition', 'diabetes', 'cardiovascular'],
    details:
      'A casual market walkthrough focused on approachable produce choices, balanced meals, and small weekly nutrition goals.',
    searchQuery: 'farmers market nutrition education',
  },
]

function addDays(date, days) {
  const nextDate = new Date(date)
  nextDate.setDate(nextDate.getDate() + days)
  return nextDate
}

export function getMockWeeklyEvents(baseDate = new Date()) {
  return mockWeeklyEventTemplates.map((event) => ({
    ...event,
    startsAt: addDays(baseDate, event.dayOffset).toISOString(),
  }))
}
