const mockWeeklyEventTemplates = [
  {
    id: 'bp-screening-westside-pharmacy',
    icon: '❤️',
    title: 'Free Blood Pressure Screening',
    dayOffset: 2,
    time: '10:00 AM',
    location: 'Westside Community Pharmacy',
    address: 'Westside Community Pharmacy',
    distance: '1.2 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'blood-pressure'],
    details:
      'A drop-in community screening where visitors can check blood pressure and learn what numbers may be useful to discuss with a healthcare professional.',
    searchQuery: 'blood pressure screening pharmacy',
  },
  {
    id: 'community-heart-walk',
    icon: '🌿',
    title: 'Community Heart Walk',
    dayOffset: 3,
    time: '9:00 AM',
    location: 'Lakeview Trail Meetup Point',
    address: 'Lakeview Trail',
    distance: '2.4 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'movement', 'mental'],
    details:
      'A beginner-friendly group walk focused on steady movement, social support, and building a repeatable weekly habit.',
    searchQuery: 'community heart walk walking trail',
  },
  {
    id: 'cholesterol-nutrition-class',
    icon: '🥗',
    title: 'Heart-Healthy Nutrition Class',
    dayOffset: 4,
    time: '6:00 PM',
    location: 'Neighborhood Wellness Center',
    address: 'Neighborhood Wellness Center',
    distance: '3.1 miles',
    cost: 'Free',
    tags: ['cardiovascular', 'cholesterol', 'nutrition'],
    details:
      'A practical class on balanced meals, fiber-rich foods, and questions to bring up when discussing cholesterol screening.',
    searchQuery: 'heart healthy nutrition class wellness center',
  },
  {
    id: 'diabetes-prevention-workshop',
    icon: '🩸',
    title: 'Diabetes Prevention Workshop',
    dayOffset: 1,
    time: '6:00 PM',
    location: 'Sunset Community Center',
    address: 'Sunset Community Center',
    distance: '2.0 miles',
    cost: 'Free',
    tags: ['diabetes', 'nutrition', 'movement'],
    details:
      'An educational workshop about healthy routines, glucose screening questions, and everyday prevention habits.',
    searchQuery: 'diabetes prevention workshop community center',
  },
  {
    id: 'healthy-cooking-demo',
    icon: '🥬',
    title: 'Healthy Cooking Demo',
    dayOffset: 5,
    time: '5:30 PM',
    location: 'Mission Farmers Market Pavilion',
    address: 'Farmers market pavilion',
    distance: '4.4 miles',
    cost: 'Free',
    tags: ['diabetes', 'nutrition', 'cardiovascular'],
    details:
      'A hands-on cooking demo with simple meal ideas that support balanced nutrition and sustainable home routines.',
    searchQuery: 'healthy cooking demo farmers market',
  },
  {
    id: 'cancer-screening-talk',
    icon: '🧬',
    title: 'Cancer Screening Education Talk',
    dayOffset: 2,
    time: '12:30 PM',
    location: 'City Health Library',
    address: 'City Health Library',
    distance: '3.8 miles',
    cost: 'Free',
    tags: ['cancer', 'screening'],
    details:
      'A community education session about screening conversations, family history, and preparing questions for a primary-care visit.',
    searchQuery: 'cancer screening education seminar',
  },
  {
    id: 'genetic-counseling-info-session',
    icon: '🧬',
    title: 'Family History & Genetic Counseling Q&A',
    dayOffset: 6,
    time: '11:00 AM',
    location: 'Regional Prevention Center',
    address: 'Regional Prevention Center',
    distance: '5.6 miles',
    cost: 'Free',
    tags: ['cancer', 'screening'],
    details:
      'An informational Q&A about when family patterns may be worth discussing with a healthcare professional or genetic counselor.',
    searchQuery: 'genetic counseling clinic family history',
  },
  {
    id: 'quit-support-group',
    icon: '🚭',
    title: 'Quit-Support Group',
    dayOffset: 1,
    time: '7:00 PM',
    location: 'Community Health Hub',
    address: 'Community Health Hub',
    distance: '2.7 miles',
    cost: 'Free',
    tags: ['smoking', 'respiratory', 'cardiovascular'],
    details:
      'A supportive group for people exploring ways to reduce or stop smoking or vaping, with education and local quit resources.',
    searchQuery: 'smoking cessation support group',
  },
  {
    id: 'mindfulness-workshop',
    icon: '🧘',
    title: 'Mindfulness for Stress Workshop',
    dayOffset: 3,
    time: '6:30 PM',
    location: 'Open Door Wellness Studio',
    address: 'Open Door Wellness Studio',
    distance: '1.9 miles',
    cost: 'Free',
    tags: ['mental', 'stress'],
    details:
      'A short workshop introducing breathing exercises, low-pressure reflection, and simple practices for stressful weeks.',
    searchQuery: 'mindfulness stress management workshop',
  },
  {
    id: 'community-yoga',
    icon: '🌱',
    title: 'Community Beginner Yoga',
    dayOffset: 4,
    time: '8:30 AM',
    location: 'Civic Recreation Center',
    address: 'Civic Recreation Center',
    distance: '3.0 miles',
    cost: 'Paid',
    tags: ['mental', 'stress', 'movement'],
    details:
      'A gentle beginner class that supports movement, flexibility, and stress management without requiring prior experience.',
    searchQuery: 'beginner yoga class recreation center',
  },
  {
    id: 'family-wellness-fair',
    icon: '✨',
    title: 'Family Wellness Fair',
    dayOffset: 5,
    time: '10:00 AM',
    location: 'Central Community Center',
    address: 'Central Community Center',
    distance: '4.1 miles',
    cost: 'Free',
    tags: ['general', 'screening', 'nutrition', 'movement'],
    details:
      'A general wellness event with prevention education, community programs, and practical resources for building healthier routines.',
    searchQuery: 'community wellness fair',
  },
  {
    id: 'farmers-market-walkthrough',
    icon: '🍎',
    title: 'Farmers Market Wellness Walkthrough',
    dayOffset: 7,
    time: '9:30 AM',
    location: 'Saturday Farmers Market',
    address: 'Saturday Farmers Market',
    distance: '2.8 miles',
    cost: 'Free',
    tags: ['general', 'nutrition', 'diabetes', 'cardiovascular'],
    details:
      'A casual market walkthrough focused on approachable produce choices, balanced meals, and small weekly nutrition goals.',
    searchQuery: 'farmers market nutrition education',
  },
]

function addDays(date, days) {
  const nextDate = new Date(date)
  nextDate.setDate(nextDate.getDate() + days)
  return nextDate
}

export function getMockWeeklyEvents(baseDate = new Date()) {
  return mockWeeklyEventTemplates.map((event) => ({
    ...event,
    startsAt: addDays(baseDate, event.dayOffset).toISOString(),
  }))
}
